In [26]:
"""Write a function so that the columns of the output matrix are powers of the input
vector.
The order of the powers is determined by the increasing boolean argument. Specifically, when
increasing is False, the i-th output column is the input vector raised element-wise to the power
of N - i - 1.
HINT: Such a matrix with a geometric progression in each row is named for Alexandre-Theophile Vandermonde."""
import pandas as pd
import numpy as np
def Fun_pow(arr,num=None,inc=False):
    if num==None:
        num=len(arr) 
    if inc==False:
        return np.array([[i**(num-j-1) for j in range(num)] for i in arr])
    elif inc==True:
        return np.array([[i**(num-j) for j in range(num,0,-1)] for i in arr])
    else:
        return "Increasing boolean argument either True or False"

a=np.array([1,2,3,5])
print(Fun_pow(a,3))
print(Fun_pow(a,3,True))

[[ 1  1  1]
 [ 4  2  1]
 [ 9  3  1]
 [25  5  1]]
[[ 1  1  1]
 [ 1  2  4]
 [ 1  3  9]
 [ 1  5 25]]


In [27]:
#Numpy Buit-in method np.vander
out_1=np.vander(a,3)
out_2=np.vander(a,3,True)
print(out_1)
print(out_2)

[[ 1  1  1]
 [ 4  2  1]
 [ 9  3  1]
 [25  5  1]]
[[ 1  1  1]
 [ 1  2  4]
 [ 1  3  9]
 [ 1  5 25]]


In [48]:
"""Problem Statement 2: Given a sequence of n values x1, x2, ..., xn and a window size k>0, the k-th moving average of the 
given sequence is defined as follows:
The moving average sequence has n-k+1 elements as shown below.
The moving averages with k=4 of a ten-value sequence (n=10) is shown below
i 1 2 3 4 5 6 7 8 9 10
===== == == == == == == == == == ==
Input 10 20 30 40 50 60 70 80 90 100
y1 25 = (10+20+30+40)/4
y2 35 = (20+30+40+50)/4
y3 45 = (30+40+50+60)/4
y4 55 = (40+50+60+70)/4
y5 65 = (50+60+70+80)/4
y6 75 = (60+70+80+90)/4
y7 85 = (70+80+90+100)/4
Thus, the moving average sequence has n-k+1=10-4+1=7 values.
Question: Write a function to find moving average in an array over a window:
Test it over [3, 5, 7, 2, 8, 10, 11, 65, 72, 81, 99, 100, 150] and window of 3."""
def Move_Avg(lst,k=1):
    if k<1:
        return "K should be greater than 1"
    n=len(lst)
    v_range=n-k+1
    result=[round(sum(lst[i:k+i])/k,2) for i in range(v_range)]
    return result
        
Move_Avg([3, 5, 7, 2, 8, 10, 11, 65, 72, 81, 99, 100, 150],3)    

[5.0, 4.67, 5.67, 6.67, 9.67, 28.67, 49.33, 72.67, 84.0, 93.33, 116.33]

In [66]:
#Numpy Buit-in method np.cumsum
def Num_cumsum(a,k):
    cumsum = np.cumsum(np.insert(a, 0, 0))
    return np.round((cumsum[k:] - cumsum[:-k]) / float(k),2)

input1=np.array([3, 5, 7, 2, 8, 10, 11, 65, 72, 81, 99, 100, 150])
Num_cumsum(input1,3)


array([  5.  ,   4.67,   5.67,   6.67,   9.67,  28.67,  49.33,  72.67,
        84.  ,  93.33, 116.33])